#' Optimise Lineups
#'
#' Calculates optimal lineups for all franchises in the dataframe based on a table of lineup constraints.
#'
#' Lineup efficiency is the percentage of optimal/best-ball score that is used as the actual score - by default, the lineup efficiency for a team in non-best-ball settings is normally distributed around a mean of 77.5% and a standard deviation of 5%.
#'
#' `lineup_method = "rank"` models the start/sit decision instead of assuming
#' an efficiency: lineups are chosen by the points a manager would *expect*
#' from each player's simulated weekly ranking (the `avg_week` column, i.e.
#' the historical average score at that weekly rank), then scored with the
#' realized simulated points. Lineup efficiency emerges from the simulation
#' (the manager benches surprise booms and starts highly-ranked duds) rather
#' than being drawn from a normal distribution. Requires projections that
#' carry weekly ranks (`version = "v2"` or `"v3"`); ignored when
#' `best_ball = TRUE`.
#'
#' @param roster_scores a dataframe as generated by `ffs_score_rosters()` - should contain columns like: projected_score, pos, and player_id
#' @param lineup_constraints a dataframe as generated by `ffscrapr::ff_starter_positions()` - should contain columns pos, min, max, and offense_starters
#' @param lineup_efficiency_mean the average lineup efficiency to use, defaults to 0.775
#' @param lineup_efficiency_sd the standard deviation of lineup efficiency, defaults to 0.05
#' @param best_ball a logical: FALSE will apply a lineup efficiency factor and TRUE uses optimal scores as actual scores, default = FALSE
# @param parallel a logical: TRUE will run the optimization in parallel, requires the furrr and future packages as well as setting `future::plan()` in advance/externally. Default FALSE.
#' @param pos_filter a character vector specifying which positions are eligible - defaults to `c("QB","RB","WR","TE)`
#' @param lineup_method one of "efficiency" (default: hindsight-optimal lineups scaled by a random efficiency factor) or "rank" (lineups set from weekly rankings like a real manager, efficiency emerges)
# @param verbose a logical: TRUE (default) will print stuff.
#'
#' @return a dataframe of what each team scored for each week
#'
#' @examples \donttest{
#' # cached examples
#' roster_scores <- .ffs_cache_example("roster_scores.rds")
#' lineup_constraints <- .ffs_cache_example("mfl_lineup_constraints.rds")
#'
#' ffs_optimise_lineups(roster_scores, lineup_constraints)
#' }
#'
#' @seealso `vignette("custom")` for example usage
#'
#' @export

ffs_optimise_lineups <- function(roster_scores,
                                 lineup_constraints,
                                 lineup_efficiency_mean = 0.775,
                                 lineup_efficiency_sd = 0.05,
                                 best_ball = FALSE,
                                 pos_filter = c("QB", "RB", "WR", "TE"),
                                 lineup_method = c("efficiency", "rank"),
                                 version = c("v2", "v1")) {
  version <- rlang::arg_match0(version, c("v2","v1"))
  lineup_method <- rlang::arg_match0(lineup_method, c("efficiency", "rank"))
  checkmate::assert_number(lineup_efficiency_mean, lower = 0, upper = 1)
  checkmate::assert_number(lineup_efficiency_sd, lower = 0, upper = 0.25)
  checkmate::assert_flag(best_ball)

  assert_df(roster_scores,
            c("pos", "pos_rank", "league_id", "franchise_id",
              "franchise_name", "season", "week", "projected_score")
  )
  # total_starters is consumed by .ff_optimise_one_lineup's constraint matrix
  assert_df(lineup_constraints, c("pos", "min", "max", "offense_starters", "total_starters"))

  if (best_ball) lineup_method <- "efficiency" # no start/sit decision in best ball

  if (lineup_method == "rank") {
    assert_df(roster_scores, "avg_week") # manager-expected points at the simulated weekly rank
  }

  roster_scores <- data.table::as.data.table(roster_scores)
  lineup_constraints <- data.table::as.data.table(lineup_constraints)
  lineup_constraints <- lineup_constraints[lineup_constraints$pos %in% pos_filter]

  max_lineup_constraints <- lineup_constraints[, c("pos", "max")]

  data.table::setkeyv(max_lineup_constraints, "pos")
  data.table::setkeyv(roster_scores, "pos")

  optimal_scores <- merge(roster_scores, max_lineup_constraints, by = "pos")

  data.table::setkeyv(optimal_scores, c("league_id", "franchise_id", "franchise_name", "season", "week"))

  # trim each roster-week to players who could plausibly start. pos_rank
  # ranks realized scores (what the hindsight-optimal lineup needs); the rank
  # method must also keep players a manager would have *expected* to start,
  # so it keeps the top-max by expected points as well
  keep <- optimal_scores$pos_rank <= optimal_scores$max
  if (lineup_method == "rank") {
    exp_rank <- NULL
    avg_week <- NULL
    optimal_scores[
      , exp_rank := data.table::frank(-data.table::fcoalesce(as.numeric(avg_week), 0),
                                      ties.method = "first"),
      by = c("league_id", "franchise_id", "pos", "season", "week")
    ]
    keep <- keep | optimal_scores$exp_rank <= optimal_scores$max
  }

  score_cols <- c("league_id", "franchise_id", "franchise_name", "season", "week",
                  "player_id", "pos", "projected_score",
                  if (lineup_method == "rank") "avg_week")

  optimal_scores <- optimal_scores[
    keep & optimal_scores$pos %in% lineup_constraints$pos,
    score_cols,
    with = FALSE
  ]

  if (lineup_method == "efficiency") {
    optimal_scores <-
      optimal_scores[
        , .ff_optimise_one_lineup(.SD, lineup_constraints)
        , by = c("league_id", "franchise_id", "franchise_name", "season", "week"),
        .SDcols = c("player_id", "pos", "projected_score")
      ]

    if (best_ball) optimal_scores[, `:=`(lineup_efficiency = 1)]

    if (!best_ball) {
      optimal_scores[, `:=`(lineup_efficiency = stats::rnorm(.N, mean = lineup_efficiency_mean, sd = lineup_efficiency_sd))]
    }

    optimal_scores[, `:=`(actual_score = optimal_scores$optimal_score * optimal_scores$lineup_efficiency)]
  }

  if (lineup_method == "rank") {
    optimal_score <- actual_score <- NULL

    optimal_scores <-
      optimal_scores[
        , c(
          .ff_optimise_one_lineup(.SD, lineup_constraints),
          .ff_rank_one_lineup(.SD, lineup_constraints)
        )
        , by = c("league_id", "franchise_id", "franchise_name", "season", "week"),
        .SDcols = c("player_id", "pos", "projected_score", "avg_week")
      ]

    optimal_scores[
      , `:=`(lineup_efficiency = data.table::fifelse(optimal_score > 0, actual_score / optimal_score, 1))
    ]
  }

  return(optimal_scores)
}

#' @rdname ffs_optimise_lineups
#' @export
ffs_optimize_lineups <- ffs_optimise_lineups

#' Optimise single lineup
#'
#' Optimises lineups for one franchise week at a time. Use purrr or loops to do more franchises/weeks/seasons
#'
#' @param franchise_scores a data frame of scores for one week and one franchise
#' @param lineup_constraints a data frame as created by `ffscrapr::ff_starter_positions()`
#'
#' @return a list including the optimal_score and the optimal_lineup.
#'
#' @keywords internal
.ff_optimise_one_lineup <- function(franchise_scores, lineup_constraints) {
  min_req <- sum(lineup_constraints$min)

  player_ids <- c(franchise_scores$player_id, rep_len(NA_character_, min_req))
  player_scores <- c(franchise_scores$projected_score, rep_len(0, min_req))
  player_scores[is.na(player_scores)] <- 0

  selected <- .ff_solve_lineup(
    objective = player_scores,
    pos = franchise_scores$pos,
    lineup_constraints = lineup_constraints
  )

  optimals <- list(
    optimal_score = sum(player_scores[selected]),
    optimal_player_id = list(player_ids[selected]),
    optimal_player_score = list(player_scores[selected])
  )


  return(optimals)
}

#' Set one lineup from weekly rankings
#'
#' Chooses starters by the points a manager would expect given each player's
#' simulated weekly rank (`avg_week`), then scores that lineup with the
#' realized simulated points - the start/sit decision as a real manager makes
#' it, without hindsight.
#'
#' @param franchise_scores a data frame of scores for one week and one franchise, incl. avg_week
#' @param lineup_constraints a data frame as created by `ffscrapr::ff_starter_positions()`
#'
#' @return a list including the realized actual_score and the started players
#'
#' @keywords internal
.ff_rank_one_lineup <- function(franchise_scores, lineup_constraints) {
  min_req <- sum(lineup_constraints$min)

  player_ids <- c(franchise_scores$player_id, rep_len(NA_character_, min_req))
  realized <- c(franchise_scores$projected_score, rep_len(0, min_req))
  realized[is.na(realized)] <- 0
  expected <- c(franchise_scores$avg_week, rep_len(0, min_req))
  expected[is.na(expected)] <- 0 # unranked player: manager expects nothing, benches him

  selected <- .ff_solve_lineup(
    objective = expected,
    pos = franchise_scores$pos,
    lineup_constraints = lineup_constraints
  )

  return(list(
    actual_score = sum(realized[selected]),
    starter_player_id = list(player_ids[selected])
  ))
}

#' Solve one lineup LP
#'
#' Shared constraint-matrix construction and Rglpk call. The objective vector
#' must already be padded with `sum(lineup_constraints$min)` zero-point
#' filler players (which count as every position) so the LP is always feasible.
#'
#' @param objective padded objective vector (points to maximise)
#' @param pos unpadded position vector of the real players
#' @param lineup_constraints a data frame as created by `ffscrapr::ff_starter_positions()`
#'
#' @return logical selection vector over the padded players
#'
#' @keywords internal
.ff_solve_lineup <- function(objective, pos, lineup_constraints) {
  min_req <- sum(lineup_constraints$min)

  # binary - position identifiers

  pos_ids <- NULL

  for (i in lineup_constraints$pos) pos_ids <- c(pos_ids, as.integer(pos == i), rep.int(1L, min_req))

  constraints_matrix <- matrix(
    c(
      pos_ids, # pos minimums
      pos_ids, # pos maximums
      as.integer(pos %in% c("QB", "RB", "WR", "TE")), rep.int(1L, min_req), # total offensive starters
      rep.int(1L, length(objective))
    ),
    nrow = nrow(lineup_constraints) * 2 + 2,
    byrow = TRUE
  )

  constraints_dir <- c(
    rep_len(">=", nrow(lineup_constraints)),
    rep_len("<=", nrow(lineup_constraints)),
    "<=",
    "<="
  )

  constraints_rhs <- c(
    lineup_constraints$min,
    lineup_constraints$max,
    lineup_constraints$offense_starters[[1]],
    lineup_constraints$total_starters[[1]]
  )

  solve_lineup <- Rglpk::Rglpk_solve_LP(
    obj = objective,
    mat = constraints_matrix,
    dir = constraints_dir,
    rhs = constraints_rhs,
    types = rep("B", length(objective)),
    max = TRUE
  )

  return(as.logical(solve_lineup$solution))
}
